controller_list:
  - name: fake_ur20_controller
    type: $(arg fake_execution_type)
    joints:
      - robot_arm_shoulder_pan_joint
      - robot_arm_shoulder_lift_joint
      - robot_arm_elbow_joint
      - robot_arm_wrist_1_joint
      - robot_arm_wrist_2_joint
      - robot_arm_wrist_3_joint
  - name: fake_liftkit_controller
    type: $(arg fake_execution_type)
    joints:
      - robot_ewellix_lift_top_joint
  - name: fake_ur20_and_liftkit_controller
    type: $(arg fake_execution_type)
    joints:
      - robot_ewellix_lift_top_joint
      - robot_arm_shoulder_pan_joint
      - robot_arm_shoulder_lift_joint
      - robot_arm_elbow_joint
      - robot_arm_wrist_1_joint
      - robot_arm_wrist_2_joint
      - robot_arm_wrist_3_joint
initial:  # Define initial robot poses per group
  - group: ur20
    pose: home
  - group: liftkit
    pose: home
  - group: ur20_and_liftkit
    pose: home